import json
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef,
    confusion_matrix, classification_report
)

ROOT = Path(__file__).resolve().parent
MODEL_DIR = ROOT / "model"

st.set_page_config(
    page_title="CRM Sales Forecasting",
    page_icon="📈",
    layout="wide"
)

st.title("📈 CRM Sales Opportunity Forecasting")
st.caption(
    "Predict Closed Won vs Closed Lost opportunities using six classification models."
)

@st.cache_data
def load_default_test():
    path = ROOT / "test_data.csv"
    if path.exists():
        return pd.read_csv(path)
    return None

@st.cache_resource
def load_model(model_name):
    path = MODEL_DIR / f"{model_name.lower().replace(' ', '_')}.joblib"
    return joblib.load(path)

@st.cache_data
def load_metadata():
    with open(MODEL_DIR / "metadata.json", "r", encoding="utf-8") as f:
        return json.load(f)

metadata = load_metadata()

st.sidebar.header("Model Selection")
model_names = metadata["models"]
selected_model = st.sidebar.selectbox("Choose model", model_names)

uploaded = st.file_uploader(
    "Upload test_data.csv",
    type=["csv"],
    help="Upload the processed test CSV generated by train_and_save.py."
)

if uploaded is not None:
    data = pd.read_csv(uploaded)
else:
    data = load_default_test()
    if data is None:
        st.warning("Please upload the processed test_data.csv file.")
        st.stop()

features = metadata["features"]
missing = [c for c in features if c not in data.columns]

if missing:
    st.error(
        "The uploaded CSV is missing required model features: "
        + ", ".join(missing)
    )
    st.stop()

st.subheader("Test Dataset")
st.write(f"Rows: {len(data):,} | Columns: {len(data.columns):,}")
st.dataframe(data.head(20), use_container_width=True)

model = load_model(selected_model)
X = data[features]

probability = model.predict_proba(X)[:, 1]

# Use the saved threshold for the selected model.
threshold = next(
    r["Decision Threshold"]
    for r in metadata["results"]
    if r["ML Model Name"] == selected_model
)

prediction = (probability >= threshold).astype(int)

results = data.copy()
results["Predicted_Class"] = prediction
results["Predicted_Label"] = np.where(
    prediction == 1, "Closed Won", "Closed Lost"
)
results["Won_Probability"] = probability

if "target" in data.columns:
    y_true = data["target"].astype(int)

    metrics = {
        "Accuracy": accuracy_score(y_true, prediction),
        "AUC": roc_auc_score(y_true, probability),
        "Precision": precision_score(y_true, prediction, zero_division=0),
        "Recall": recall_score(y_true, prediction, zero_division=0),
        "F1 Score": f1_score(y_true, prediction, zero_division=0),
        "MCC": matthews_corrcoef(y_true, prediction)
    }

    st.subheader(f"Evaluation Metrics — {selected_model}")

    c1, c2, c3 = st.columns(3)
    c1.metric("Accuracy", f"{metrics['Accuracy']:.4f}")
    c2.metric("AUC", f"{metrics['AUC']:.4f}")
    c3.metric("Precision", f"{metrics['Precision']:.4f}")

    c4, c5, c6 = st.columns(3)
    c4.metric("Recall", f"{metrics['Recall']:.4f}")
    c5.metric("F1 Score", f"{metrics['F1 Score']:.4f}")
    c6.metric("MCC", f"{metrics['MCC']:.4f}")

    st.caption(f"Decision threshold used: {threshold:.2f}")

    st.subheader("Confusion Matrix")
    cm = confusion_matrix(y_true, prediction)

    fig, ax = plt.subplots(figsize=(5, 4))
    im = ax.imshow(cm)
    ax.set_xticks([0, 1])
    ax.set_yticks([0, 1])
    ax.set_xticklabels(["Closed Lost", "Closed Won"])
    ax.set_yticklabels(["Closed Lost", "Closed Won"])
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    ax.set_title(f"{selected_model} — Confusion Matrix")

    for i in range(2):
        for j in range(2):
            ax.text(j, i, cm[i, j], ha="center", va="center")

    st.pyplot(fig, use_container_width=False)
    plt.close(fig)

    st.subheader("Classification Report")
    report = classification_report(
        y_true,
        prediction,
        target_names=["Closed Lost", "Closed Won"],
        output_dict=True,
        zero_division=0
    )
    st.dataframe(pd.DataFrame(report).transpose(), use_container_width=True)

else:
    st.info(
        "The uploaded file does not contain the target column, so evaluation "
        "metrics cannot be calculated. Upload the generated test_data.csv "
        "for the assignment demonstration."
    )

st.subheader("Prediction Results")
st.dataframe(results.head(100), use_container_width=True)

csv = results.to_csv(index=False).encode("utf-8")
st.download_button(
    "Download Prediction Results",
    data=csv,
    file_name="prediction_results.csv",
    mime="text/csv"
)
